"""Second migration

Revision ID: c7a5a940aee0
Revises: ff66efd0c005
Create Date: 2024-12-19 20:14:53.631007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a5a940aee0'
down_revision: Union[str, None] = 'ff66efd0c005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtasks', 'lead_time')
    op.drop_column('subtasks', 'due_date')
    op.drop_column('tasks', 'lead_time')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_date', sa.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('lead_time', sa.TIME(), nullable=True))
    op.add_column('subtasks', sa.Column('due_date', sa.DATETIME(), nullable=True))
    op.add_column('subtasks', sa.Column('lead_time', sa.TIME(), nullable=True))
    # ### end Alembic commands ###
